# Generated by Django 4.0.5 on 2022-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []
    

    operations = []
